apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-ia
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Para que n8n y Ollama compartan datos
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-ia # Clase manual para evitar el provisioner dinamico
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a0ef43bc6dae9f9b # <--- COLOCA TU FS-ID DE EFS AQUÍ
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-ia
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-ia
  volumeName: efs-pv-ia # Vincula el PVC al PV específico
  resources:
    requests:
      storage: 20Gi